---
# Ensure basic utilities are installed
- name: Ensure necessary packages are installed
  package:
    name:
      - vim
      - curl
      - git
      - tree
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present