---

# Ensure basic utilities are installed
- name: Ensure necessary packages are installed
  package:
    name:
      - vim
      - curl
      - git
      - tree
      - python3-pip
    state: present