---
# installation de Kubernetes 1.30 sur Ubuntu 22.04 (jammy)
- name: Add Kubernetes GPG key
  shell: sudo mkdir -p /etc/apt/keyrings | curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg | sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold kubelet, kubeadm, and kubectl at current version
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold

- name: Disable swap
  command: swapoff -a
  when: ansible_virtualization_type != "docker"

